name: Deploy on Render

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Render CLI
        run: pip install render-cli

      - name: Deploy to Render
        run: |
          # Update service name if not "aiprofit-stripe-api"
          render services update aiprofit-stripe-api \
            --branch main \
            --autoDeploy true
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
